apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask-demo
  ports:
    - protocol: TCP
      port: 80         # Service port (outside)
      targetPort: 5000 # Flask app port inside container
  type: NodePort       # Expose app externally in PWK
